site_name: MEKA
theme: readthedocs
repo_url: https://github.com/Waikato/meka
site_description: MEKA Documentation
markdown_extensions:
  - toc:
      baselevel: 2
      permalink: "#"
plugins:
  - search
pages:
    - MEKA: index.md
    - News: news.md
    - Documentation: documentation.md
    - Downloads: downloads.md
    - Datasets: datasets.md
    - Citing: citing.md
    - Maven: maven.md
    - An Overview of Methods in MEKA: methods.md
    - Methods (API):
        - meka.classifiers.multilabel.BCC: meka.classifiers.multilabel.BCC.md
        - meka.classifiers.multilabel.BPNN: meka.classifiers.multilabel.BPNN.md
        - meka.classifiers.multilabel.BR: meka.classifiers.multilabel.BR.md
        - meka.classifiers.multilabel.BRq: meka.classifiers.multilabel.BRq.md
        - meka.classifiers.multilabel.CC: meka.classifiers.multilabel.CC.md
        - meka.classifiers.multilabel.CCq: meka.classifiers.multilabel.CCq.md
        - meka.classifiers.multilabel.CDN: meka.classifiers.multilabel.CDN.md
        - meka.classifiers.multilabel.CDT: meka.classifiers.multilabel.CDT.md
        - meka.classifiers.multilabel.CT: meka.classifiers.multilabel.CT.md
        - meka.classifiers.multilabel.DBPNN: meka.classifiers.multilabel.DBPNN.md
        - meka.classifiers.multilabel.FW: meka.classifiers.multilabel.FW.md
        - meka.classifiers.multilabel.HASEL: meka.classifiers.multilabel.HASEL.md
        - meka.classifiers.multilabel.incremental.BRUpdateable: meka.classifiers.multilabel.incremental.BRUpdateable.md
        - meka.classifiers.multilabel.incremental.CCUpdateable: meka.classifiers.multilabel.incremental.CCUpdateable.md
        - meka.classifiers.multilabel.incremental.MajorityLabelsetUpdateable: meka.classifiers.multilabel.incremental.MajorityLabelsetUpdateable.md
        - meka.classifiers.multilabel.incremental.meta.BaggingMLUpdateable: meka.classifiers.multilabel.incremental.meta.BaggingMLUpdateable.md
        - meka.classifiers.multilabel.incremental.PSUpdateable: meka.classifiers.multilabel.incremental.PSUpdateable.md
        - meka.classifiers.multilabel.incremental.RTUpdateable: meka.classifiers.multilabel.incremental.RTUpdateable.md
        - meka.classifiers.multilabel.LC: meka.classifiers.multilabel.LC.md
        - meka.classifiers.multilabel.MajorityLabelset: meka.classifiers.multilabel.MajorityLabelset.md
        - meka.classifiers.multilabel.Maniac: meka.classifiers.multilabel.Maniac.md
        - meka.classifiers.multilabel.MCC: meka.classifiers.multilabel.MCC.md
        - meka.classifiers.multilabel.meta.BaggingML: meka.classifiers.multilabel.meta.BaggingML.md
        - meka.classifiers.multilabel.meta.BaggingMLdup: meka.classifiers.multilabel.meta.BaggingMLdup.md
        - meka.classifiers.multilabel.meta.CM: meka.classifiers.multilabel.meta.CM.md
        - meka.classifiers.multilabel.meta.DeepML: meka.classifiers.multilabel.meta.DeepML.md
        - meka.classifiers.multilabel.meta.EM: meka.classifiers.multilabel.meta.EM.md
        - meka.classifiers.multilabel.meta.EnsembleML: meka.classifiers.multilabel.meta.EnsembleML.md
        - meka.classifiers.multilabel.meta.ERFH: meka.classifiers.multilabel.meta.ERFH.md
        - meka.classifiers.multilabel.meta.FilteredClassifier: meka.classifiers.multilabel.meta.FilteredClassifier.md
        - meka.classifiers.multilabel.meta.HOMER: meka.classifiers.multilabel.meta.HOMER.md
        - meka.classifiers.multilabel.meta.MBR: meka.classifiers.multilabel.meta.MBR.md
        - meka.classifiers.multilabel.meta.MLRF: meka.classifiers.multilabel.meta.MLRF.md
        - meka.classifiers.multilabel.meta.MultiSearch: meka.classifiers.multilabel.meta.MultiSearch.md
        - meka.classifiers.multilabel.meta.RandomSubspaceML: meka.classifiers.multilabel.meta.RandomSubspaceML.md
        - meka.classifiers.multilabel.meta.SubsetMapper: meka.classifiers.multilabel.meta.SubsetMapper.md
        - meka.classifiers.multilabel.MLCBMaD: meka.classifiers.multilabel.MLCBMaD.md
        - meka.classifiers.multilabel.MULAN: meka.classifiers.multilabel.MULAN.md
        - meka.classifiers.multilabel.PCC: meka.classifiers.multilabel.PCC.md
        - meka.classifiers.multilabel.PLST: meka.classifiers.multilabel.PLST.md
        - meka.classifiers.multilabel.PMCC: meka.classifiers.multilabel.PMCC.md
        - meka.classifiers.multilabel.PS: meka.classifiers.multilabel.PS.md
        - meka.classifiers.multilabel.PSt: meka.classifiers.multilabel.PSt.md
        - meka.classifiers.multilabel.RAkEL: meka.classifiers.multilabel.RAkEL.md
        - meka.classifiers.multilabel.RAkELd: meka.classifiers.multilabel.RAkELd.md
        - meka.classifiers.multilabel.RT: meka.classifiers.multilabel.RT.md
        - meka.classifiers.multitarget.BCC: meka.classifiers.multitarget.BCC.md
        - meka.classifiers.multitarget.CC: meka.classifiers.multitarget.CC.md
        - meka.classifiers.multitarget.CCp: meka.classifiers.multitarget.CCp.md
        - meka.classifiers.multitarget.CR: meka.classifiers.multitarget.CR.md
        - meka.classifiers.multitarget.meta.BaggingMT: meka.classifiers.multitarget.meta.BaggingMT.md
        - meka.classifiers.multitarget.meta.EnsembleMT: meka.classifiers.multitarget.meta.EnsembleMT.md
        - meka.classifiers.multitarget.meta.FilteredClassifier: meka.classifiers.multitarget.meta.FilteredClassifier.md
        - meka.classifiers.multitarget.meta.MultiSearch: meka.classifiers.multitarget.meta.MultiSearch.md
        - meka.classifiers.multitarget.NSR: meka.classifiers.multitarget.NSR.md
        - meka.classifiers.multitarget.RAkELd: meka.classifiers.multitarget.RAkELd.md
        - meka.classifiers.multitarget.SCC: meka.classifiers.multitarget.SCC.md
