/*
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * AbstractTabMenuItem.java
 * Copyright (C) 2016 University of Waikato, Hamilton, NZ
 */

package meka.gui.explorer;

import javax.swing.JMenuItem;
import java.awt.event.ActionListener;
import java.util.HashMap;

/**
 * Ancestor to classes that can be added to a tab's custom menu.
 *
 * @author FracPete (fracpete at waikato dot ac dot nz)
 * @version $Revision$
 */
public abstract class AbstractTabMenuItem<T extends AbstractExplorerTab>
	implements Comparable<AbstractTabMenuItem<T>> {

	/**
	 * Checks whether a session value is present.
	 *
	 * @param owner		the tab this menu item belongs to
	 * @param key       the key to look for
	 * @return          true if present
	 */
	public boolean hasSessionValue(T owner, String key) {
		if (owner.getSession().containsKey(getClass())) {
			return owner.getSession().get(getClass()).containsKey(key);
		}
		return false;
	}

	/**
	 * Returns a session value, if present.
	 *
	 * @param owner		the tab this menu item belongs to
	 * @param key       the key to look for
	 * @return          the value, null if not present
	 */
	public Object getSessionValue(T owner, String key) {
		if (owner.getSession().containsKey(getClass())) {
			return owner.getSession().get(getClass()).get(key);
		}
		return null;
	}

	/**
	 * Sets a session value.
	 *
	 * @param owner		the tab this menu item belongs to
	 * @param key       the key to look for
	 * @param value     the value to set
	 */
	public void setSessionValue(T owner, String key, Object value) {
		if (!owner.getSession().containsKey(getClass()))
			owner.getSession().put(getClass(), new HashMap<String, Object>());
		owner.getSession().get(getClass()).put(key, value);
	}

	/**
	 * Returns the group of the plugin. Used for the grouping the menu items.
	 *
	 * @return          the group
	 */
	public abstract String getGroup();

	/**
	 * Returns the name of the plugin. Used for the menu item text.
	 *
	 * @return          the name
	 */
	public abstract String getName();

	/**
	 * Returns the name of the icon to use.
	 *
	 * @return          the name of the icon, null if none to use
	 */
	public abstract String getIcon();

	/**
	 * Returns the action lister to use in the menu.
	 *
	 * @return          the listener
	 */
	public abstract ActionListener getActionListener(T owner);

	/**
	 * Updates the menu item using the current state of the tab.
	 *
	 * @param owner the tab that the menu item belongs to
	 * @param menuitem the menu item to update (was generated by this class)
	 */
	public abstract void update(T owner, JMenuItem menuitem);

	/**
	 * Compares this item to another, using group and name.
	 *
	 * @param o			the other item
	 * @return			less than 0, equal to 0, greater than 0 if the this item
	 * 					group/name is smaller, equal to or greater than the
	 * 					specified one
	 */
	@Override
	public int compareTo(AbstractTabMenuItem<T> o) {
		int		result;

		result = getGroup().compareTo(o.getGroup());
		if (result == 0)
			result = getName().compareTo(o.getName());

		return result;
	}
}
